language: python
notifications:
  email: false
python:
  - "3.6"
# environment variables
env:
   system_site_packages: true
# command to install dependencies
install:
  - pip install -r Lab1-2/requirements/requirements.txt
# command to run tests
script: 
  - python Lab1-2/src/test.py