language: python
python:
  - "3.6"
# environment variables
env:
  - DJANGO_VERSION=2.0.2
# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements/requirements.txt
# command to run tests
script: test
